
[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Atelierdune.light.toml"
]

[window]
opacity = 0.5
decorations = "full"

  [window.padding]
  x = 10
  y = 10

[font]
size = 13

  [font.normal]
  family = "JetBrains Mono"
  style = "Regular"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[selection]
save_to_clipboard = true
