[window]
opacity = 0.9
padding = { x = 10, y = 10 }
decorations = "None"

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[selection]
save_to_clipboard = true
