[general]
import = [
  "~/.config/alacritty/colors.toml"
]


[window]
opacity = 0.5
decorations = "none"

  [window.padding]
  x = 20
  y = 20

[font]
size = 13

  [font.normal]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"



[selection]
save_to_clipboard = true

