[colors.primary]
background = "#111418"
foreground = "#e1e2e8"

[colors.cursor]
text = "#111418"
cursor = "#a1cafd"

[colors.normal]
black   = "#111418"
red     = "#ffb4ab"
green   = "#a1cafd"
yellow  = "#d7bee4"
blue    = "#d2e4ff"
magenta = "#d7e3f8"
cyan    = "#bbc7db"
white   = "#e1e2e8"

[colors.bright]
black   = "#36393e"
red     = "#ffb4ab"
green   = "#a1cafd"
yellow  = "#d7bee4"
blue    = "#d2e4ff"
magenta = "#d7e3f8"
cyan    = "#bbc7db"
white   = "#e1e2e8"
