[colors.primary]
background = "#101418"
foreground = "#e0e2e8"

[colors.cursor]
text = "#101418"
cursor = "#99ccfa"

[colors.normal]
black   = "#101418"
red     = "#ffb4ab"
green   = "#99ccfa"
yellow  = "#d2bfe7"
blue    = "#cde5ff"
magenta = "#d4e4f6"
cyan    = "#b8c8da"
white   = "#e0e2e8"

[colors.bright]
black   = "#36393e"
red     = "#ffb4ab"
green   = "#99ccfa"
yellow  = "#d2bfe7"
blue    = "#cde5ff"
magenta = "#d4e4f6"
cyan    = "#b8c8da"
white   = "#e0e2e8"
