[colors.primary]
background = "#111318"
foreground = "#e2e2e9"

[colors.cursor]
text = "#111318"
cursor = "#aac7ff"

[colors.normal]
black   = "#111318"
red     = "#ffb4ab"
green   = "#aac7ff"
yellow  = "#ddbce0"
blue    = "#d7e3ff"
magenta = "#dae2f9"
cyan    = "#bec6dc"
white   = "#e2e2e9"

[colors.bright]
black   = "#37393e"
red     = "#ffb4ab"
green   = "#aac7ff"
yellow  = "#ddbce0"
blue    = "#d7e3ff"
magenta = "#dae2f9"
cyan    = "#bec6dc"
white   = "#e2e2e9"
