[colors.primary]
background = "#0f1416"
foreground = "#dee3e5"

[colors.cursor]
text = "#0f1416"
cursor = "#84d2e6"

[colors.normal]
black   = "#0f1416"
red     = "#ffb4ab"
green   = "#84d2e6"
yellow  = "#bec5eb"
blue    = "#a9edff"
magenta = "#cee7ee"
cyan    = "#b2cbd2"
white   = "#dee3e5"

[colors.bright]
black   = "#343a3c"
red     = "#ffb4ab"
green   = "#84d2e6"
yellow  = "#bec5eb"
blue    = "#a9edff"
magenta = "#cee7ee"
cyan    = "#b2cbd2"
white   = "#dee3e5"
