[colors.primary]
background = "#121318"
foreground = "#e2e2e9"

[colors.cursor]
text = "#121318"
cursor = "#b0c6ff"

[colors.normal]
black   = "#121318"
red     = "#ffb4ab"
green   = "#b0c6ff"
yellow  = "#e0bbde"
blue    = "#d9e2ff"
magenta = "#dce2f9"
cyan    = "#bfc6dc"
white   = "#e2e2e9"

[colors.bright]
black   = "#38393f"
red     = "#ffb4ab"
green   = "#b0c6ff"
yellow  = "#e0bbde"
blue    = "#d9e2ff"
magenta = "#dce2f9"
cyan    = "#bfc6dc"
white   = "#e2e2e9"
