[colors.primary]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"

[colors.cursor]
text = "{{colors.surface.default.hex}}"
cursor = "{{colors.primary.default.hex}}"

[colors.normal]
black   = "{{colors.surface.default.hex}}"
red     = "{{colors.error.default.hex}}"
green   = "{{colors.primary.default.hex}}"
yellow  = "{{colors.tertiary.default.hex}}"
blue    = "{{colors.on_primary_container.default.hex}}"
magenta = "{{colors.on_secondary_container.default.hex}}"
cyan    = "{{colors.secondary.default.hex}}"
white   = "{{colors.on_surface.default.hex}}"

[colors.bright]
black   = "{{colors.surface_bright.default.hex}}"
red     = "{{colors.error.default.hex}}"
green   = "{{colors.primary.default.hex}}"
yellow  = "{{colors.tertiary.default.hex}}"
blue    = "{{colors.on_primary_container.default.hex}}"
magenta = "{{colors.on_secondary_container.default.hex}}"
cyan    = "{{colors.secondary.default.hex}}"
white   = "{{colors.on_surface.default.hex}}"
